### PR TITLE
Missing attributes

### PR DESCRIPTION
**Pull request by zeroXten**
[Review on Reviewable](https://reviewable.io/reviews/simplefinance/chef-influxdb/59)

### CODE REVIEW

**Comment by jakedavis** [comment]
Can you explain the impact of these attributes? Are they defaults?

**Comment by kri5** [comment]
:+1:

**Comment by fishnix** [comment]
Hi @zeroXten thanks for the PR!  Is this still applicable?  If so, can you fix your conflicts and we can have a look?  Thanks!

**Comment by bdangit** [comment]
lets close this in favor of whats in master currently and #90

**Comment by fishnix** [comment]
agree with @bdangit

**Pull request closed without merging**
