### PR TITLE
Update for Influxdb 0.10

### PR DESCRIPTION
**Pull request by bdangit**
* Updated attributes to support Influxdb 0.10.0
* Set default resource actions (:create is default)
* Fixed support for Chef-Client 12.6+
* Fixed rubocop styling
* Added functional test to check restarts service restarts on config change

### CODE REVIEW

**Comment by fishnix** [comment]
I just read through this quickly and it looks good!  I'll run through some testing and give the thumbs up soon.  Thanks for doing this.

**Comment by fishnix** [comment]
Sorry it's taken me so long... 

Running the default-centos-67-chef124 kitchen tests I'm getting 

```
           ================================================================================
           Error executing action `create` on resource 'influxdb_config[/etc/influxdb/influxdb.conf]'
           ================================================================================

           NoMethodError
           -------------
           undefined method `file' for LWRP resource influxdb_config from cookbook influxdb

           Cookbook Trace:
           ---------------
           /tmp/kitchen/cache/cookbooks/influxdb/resources/config.rb:13:in `block in class_from_file'

           Resource Declaration:
           ---------------------
           # In /tmp/kitchen/cache/cookbooks/influxdb/recipes/default.rb

            35: influxdb_config node['influxdb']['config_file_path'] do
            36:   config node['influxdb']['config']
            37: end
            38:

           Compiled Resource:
           ------------------
           # Declared in /tmp/kitchen/cache/cookbooks/influxdb/recipes/default.rb:35:in `from_file'

           influxdb_config("/etc/influxdb/influxdb.conf") do
             action [:create]
             retries 0
             retry_delay 2
             default_guard_interpreter :default
             declared_type :influxdb_config
             cookbook_name "influxdb"
             recipe_name "default"
             config {"reporting-disabled"=>false, "meta"=>{"enabled"=>true, "dir"=>"/var/lib/influxdb/meta", "bind-address"=>":8088", "retention-autocreate"=>true, "election-timeout"=>"1s", "heartbeat-timeout"=>"1s", "leader-lease-timeout"=>"500ms", "commit-timeout"=>"50ms", "cluster-tracing"=>false}, "data"=>{"enabled"=>true, "dir"=>"/var/lib/influxdb/data", "engine"=>"tsm1", "max-wal-size"=>104857600, "wal-flush-interval"=>"10m0s", "wal-partition-flush-delay"=>"2s", "wal-dir"=>"/var/lib/influxdb/wal", "wal-enable-logging"=>true, "data-logging-enabled"=>true}, "hinted-handoff"=>{"enabled"=>true, "dir"=>"/var/lib/influxdb/hh", "max-size"=>1073741824, "max-age"=>"168h0m0s", "retry-rate-limit"=>0, "retry-interval"=>"1s", "retry-max-interval"=>"1m0s", "purge-interval"=>"1h0m0s"}, "cluster"=>{"write-timeout"=>"10s", "shard-writer-timeout"=>"5s"}, "retention"=>{"enabled"=>true, "check-interval"=>"30m0s"}, "shard-precreation"=>{"enabled"=>true, "check-interval"=>"10m0s", "advance-period"=>"30m0s"}, "monitor"=>{"store-enabled"=>true, "store-database"=>"_internal", "store-interval"=>"10s"}, "admin"=>{"enabled"=>true, "bind-address"=>":8083", "https-enabled"=>false, "https-certificate"=>"/etc/ssl/influxdb.pem"}, "http"=>{"enabled"=>true, "bind-address"=>":8086", "auth-enabled"=>false, "log-enabled"=>true, "write-tracing"=>false, "pprof-enabled"=>false, "https-enabled"=>false, "https-certificate"=>"/etc/ssl/influxdb.pem"}, "graphite"=>[{"enabled"=>false}], "collectd"=>{"enabled"=>false}, "opentsdb"=>{"enabled"=>false}, "udp"=>[{"enabled"=>false}], "continuous_queries"=>{"log-enabled"=>true, "enabled"=>true, "run-interval"=>"1s"}, "subscriber"=>{"enabled"=>true}}
             path "/etc/influxdb/influxdb.conf"
           end
```

I'm guessing its a problem with the compat_resources plugin.  I haven't had a chance to look into it yet.

**Comment by bdangit** [comment]
Hrmm. I tried to unpin compat since it's now at 12.7.1. Fails for 12.6 on the config-change suite.  Will have to investigate again.

**Comment by bdangit** [comment]
@fishnix I set the compat_resource to a branch that fixes support for 12.6.  I ran TK against centos-124 and centos-126.  Let me know what you think.

**Comment by bdangit** [comment]
```
default-centos-67-chef126          Vagrant  ChefZero     Busser    Ssh        Verified
default-centos-71-chef126          Vagrant  ChefZero     Busser    Ssh        Verified
default-centos-67-chef124          Vagrant  ChefZero     Busser    Ssh        Verified
default-centos-71-chef124          Vagrant  ChefZero     Busser    Ssh        Verified
config-change-centos-67-chef126    Vagrant  ChefZero     Busser    Ssh        Verified
config-change-centos-71-chef126    Vagrant  ChefZero     Busser    Ssh        Verified
config-change-centos-67-chef124    Vagrant  ChefZero     Busser    Ssh        Verified
config-change-centos-71-chef124    Vagrant  ChefZero     Busser    Ssh        Verified
```

```
default-centos-67-chef126           Docker  ChefZero     Busser    Ssh        Verified
default-centos-71-chef126           Docker  ChefZero     Busser    Ssh        Verified
config-change-centos-67-chef126     Docker  ChefZero     Busser    Ssh        Verified
config-change-centos-71-chef126     Docker  ChefZero     Busser    Ssh        Verified
```

**Comment by fishnix** [comment]
Cool, looks good to me @bdangit ! :+1:

**Pull request merged**
