### PR TITLE
issue #107

### PR DESCRIPTION
**Pull request by cyberflow**

### CODE REVIEW

**Comment by bdangit** [comment]
@cyberflow looks good.  before approving this, can you add a ChefSpec matcher in here: https://github.com/bdangit/chef-influxdb/blob/master/libraries/matchers.rb ?

**Comment by cyberflow** [comment]
@bdangit Done

**Comment by bdangit** [comment]
Great! And one more nit. If you can squash your git commit. 

:smile:

**Comment by fishnix** [comment]
This looks good to me! 👍

**Comment by bdangit** [comment]
👍

**Pull request merged**
