### PR TITLE
Add missing config sections for 0.9.0

### PR DESCRIPTION
**Pull request by cmjosh**
The influxdb service can't be started with the default config.  Primarily, the "meta" section was missing.  There were also a couple other missing sections that I added for consistency.

### CODE REVIEW

**Comment by sethdmoore** [comment]
:+1: 
Just ran into this today. InfluxDB fails to start without these changes.
As a hack, I just pulled in creativemarket's default.rb attributes file.

**Comment by jakedavis** [comment]
Yo @cmjosh, supremely apologetic for having left this here for so long. I just merged #66 which included rearranging some attributes to make more sense for the non-BC changes. I think as such you'll need to rebase on that, if you're still looking to get this merged. Sorry again for the delay.

**Comment by fishnix** [comment]
Hey @cmjosh, is this still relevant?  The only concern I have here is that things are moving quickly with influx and config sections may break later versions.  Can you ensure we are pulling in config attributes that are required?

**Comment by bdangit** [comment]
this will probably be the case until influxdb says we are major 1.x. However, there are ways to ensure this doesn't become a problem by creating a config of your choice and then include_recipe 'influxdb::default'. The cookbook has the attribute exposed so you can do this in the face of breaking changes. 

re-open if you are unable to do so.

**Pull request closed without merging**
