### PR TITLE
Fix install of influxdb

### PR DESCRIPTION
**Pull request by bdangit**
This PR should address issue with #144 and clean up support for Chef 13.

- `node['influxdb']['include_repository']` was getting set to `nil` even
though custom resource `influxdb_install` set `include_repository`
default to false.  To fix needed to set the node attribute to be set
properly
- fixed rubocop styling
- fixed foodcritic lints
- updated kitchen to test for Chef 13
- updated wercker profile to use latest and greatest chefdk

Signed-off-by: Ben Dang <me@bdang.it>

### CODE REVIEW

**Comment by bdangit** [comment]
At the moment, I'm passing it through Test Kitchen setups.  Once good we'll merge this in.

**Comment by bdangit** [comment]
Tested this against 12.1 chef client and its failing.  At this point, everyone should be on 12.5 or better.  Any objections to removing support fro 12.1-12.4 ?

**Comment by dmigous** [comment]
@bdangit yes, works fine. Thank you!

**Comment by bdangit** [comment]
No worries.  I'm heavily going to go based on the sister chef cookbook https://github.com/NorthPage/telegraf-cookbook#requirements which requires 12.5+.

Furthermore, 12.1 is about 2-3 years old!

**Comment by fishnix** [comment]
I'm all for dumping support of old Chef, looking good 👍

**Pull request merged**
