### PR TITLE
Bump version

### PR DESCRIPTION
**Pull request by bdangit**
Signed-off-by: Ben Dang <me@bdang.it>

### CODE REVIEW

**Comment by fishnix** [comment]
Do it to it! 👍

**Comment by bdangit** [comment]
thanks @fishnix -- i'm gated by automation.  Need to get some time to debug the wercker setup.

**Comment by fishnix** [comment]
Yeah I noticed that - I'm swamped too, if I get a chance I'll keep it on my radar

**Comment by bdangit** [comment]
all good now! 

:+1:

**Pull request merged**
