### PR TITLE
Install InfluxDB 1.0.2

### PR DESCRIPTION
**Pull request by eheydrick**
* Bumps installation version and tests to 1.0.2

### CODE REVIEW

**Comment by bdangit** [comment]
thanks for this. 👍

**Comment by eheydrick** [comment]
I ran into dpkg prompting to confirm overwriting influxdb.conf when the package is upgraded. We could solve this by passing dpkg force options. Thoughts?

**Comment by bdangit** [comment]
Oh. It sounds like influxdb package really wants to maintain the
configuration file.

We could do a force or we could leave the default config file alone and
have anyone have a custom conf file store into another spot that's always
managed by chef.

Only problem is we would have to modify the service init config to use this
new spot.

In that sense I'm okay with passing in force. I guess at least this way
chef will always make sure the version you specify will be what you expect
it.

**Comment by eheydrick** [comment]
Sounds good, I'll cut a PR for passing force.

**Pull request merged**
